project_id = "swuryncvasdwlxtwagnb"

[auth]
enabled = true
site_url = "http://localhost:54323"

[functions.process-comment]
verify_jwt = false

[functions.generate-caption]
verify_jwt = false

[functions.generate-video-metadata]
verify_jwt = false

[functions.youtube-upload]
verify_jwt = false

[functions.youtube-oauth]
verify_jwt = false

[functions.generate-channel-setup]
verify_jwt = false